import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AuthProvider}  from "./context/AuthContext ";
import ToastProvider from "./ui/ToastProvider"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Amazon Clone",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  // const session = useAuthState(auth);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {children}
           <ToastProvider /> 
        </AuthProvider>
      </body>

      
    </html>
  );
}
